### PR TITLE
Faq+Footer

### PR DESCRIPTION
**Pull request by engsung**
FAQ
Screen Shot 2021-09-30 at 12 31 11 AM

### CODE REVIEW

**Comment by JankiChaudhari226** [comment]
Change the font colour and also change the colour of "+" based on the Figma file.

 Gradient font for the header, please look at the branch - " button + font" to get the CSS for the gradient font for the heading

**Comment by engsung** [comment]
@JankiChaudhari226 here are the new changes
Screen Shot 2021-10-02 at 6 07 08 PM

Screen Shot 2021-10-02 at 6 07 22 PM

pls disregard the footer branch - the new updates are made over here!

**Comment by JankiChaudhari226** [comment]
Thank you eng! I pushed some changed to the footer branch, can you please take a look? Added footer splash and changed drop shadow for "Shoot us an email". The FAQ section looks good!

**Comment by engsung** [comment]
@JankiChaudhari226 I added the new footer changes to this branch! I think it looks good :))


Screen Shot 2021-10-02 at 7 24 29 PM

**Comment by JankiChaudhari226** [comment]
Merging! This looks good.

**Pull request merged**
